# Generated by Django 6.0.5 on 2026-08-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_address_remove_student_no_author_publisher_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='book', to='myapp.author'),
        ),
    ]
